name: google_vision_flutter
description: Add Google Visions image labeling, face, logo, and landmark detection into your Flutter applications.
version: 2.0.0+10
repository: https://github.com/cdavis-code/google_vision_workspace
homepage: https://github.com/cdavis-code/google_vision_workspace/tree/main/packages/google_vision_flutter

topics:
  - api
  - widget
  - flutter
  - image
  - document

funding:
  - https://www.buymeacoffee.com/faithoflif2

resolution: workspace

environment:
  sdk: ^3.8.0
  flutter: ">=3.16.0"

dependencies:
  dio: ^5.9.0
  flutter_image_converter: ^0.4.1
  google_vision: ^2.0.0+10
  image: ^4.5.3
  loggy: ^2.0.3

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
