library;

// DO NOT EDIT THIS FILE
// THIS FILE IS AUTOMATICALLY OVER WRITTEN BY PublishTools
import 'dart:convert' show json;

final pubSpec = json.decode(
  '{"description":"A CLI tool for making API requests to Google Vision API using the google_vision package.","homepage":"https://github.com/faithoflifedev/google_vision_workspace/tree/main/packages/google_vision_cli","name":"google_vision_cli","version":"2.0.0+10"}',
);
