name: google_vision
description: Allows you to add Google Visions image labeling, face, logo, and landmark detection, OCR, and detection of explicit content, into cross platform applications.
version: 2.2.1
repository: https://github.com/cdavis-code/google_vision_workspace
homepage: https://github.com/cdavis-code/google_vision_workspace/tree/main/packages/google_vision
issue_tracker: https://github.com/cdavis-code/google_vision_workspace/issues

topics:
  - api
  - image
  - document

funding:
  - https://www.buymeacoffee.com/cdavis

resolution: workspace

environment:
  sdk: ^3.12.0

dependencies:
  collection: ^1.19.1
  crypto_keys: ^0.3.0+1
  dio: ^5.9.2
  flutter_loggy_dio: ^3.1.0
  http: ^1.6.0
  image: ^4.8.0
  jose: ^0.3.5+2
  json_annotation: ^4.12.0
  loggy: ^2.0.3
  mime: ^2.0.0
  retrofit: ^4.9.2
  universal_platform: ^1.1.0

dev_dependencies:
  build_runner: ^2.15.0
  json_serializable: ^6.14.0
  lints: ^6.1.0
  retrofit_generator: ^10.2.6
